#!/usr/bin/env python3
"""Apply a screen-space rim lens to the glass surfaces of the Omarchy shell.

GlassLens sends the visible glass rectangles in window coordinates. Hyprland's
layer list places each window on screen; one generated screen_shader then
refracts real desktop pixels across every rim. Another user's shader is never
replaced.
"""

import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys


RUNTIME = Path(os.environ.get("XDG_RUNTIME_DIR", "/tmp"))
PREFIX = "widget-on-glass-lens-"
LEGACY = "widget-on-glass-menu-lens.frag"  # menu-only helper of earlier versions
MAX_RECTS = 32


def hyprctl(*args):
    return subprocess.run(["hyprctl", *args], check=True, capture_output=True, text=True).stdout


def screen_shader():
    return json.loads(hyprctl("-j", "getoption", "decoration:screen_shader"))["str"]


def unset(path):
    return path in ("", "[[EMPTY]]")


def owned(path):
    return unset(path) or Path(path).name.startswith(PREFIX) or Path(path).name == LEGACY


def set_shader(path):
    value = json.dumps(str(path), ensure_ascii=True)
    hyprctl("eval", f"hl.config({{ decoration = {{ screen_shader = {value} }} }})")


def remove_stale(keep=None):
    for path in RUNTIME.glob(PREFIX + "*.frag"):
        if path != keep:
            path.unlink(missing_ok=True)
    (RUNTIME / LEGACY).unlink(missing_ok=True)


def clear():
    current = screen_shader()
    if not unset(current) and owned(current):
        set_shader("")
    remove_stale()


def lens_allowed():
    """Respect the glass switches in shell.json, user file first."""
    omarchy = os.environ.get("OMARCHY_PATH", "/usr/share/omarchy")
    for path in (Path.home() / ".config/omarchy/shell.json", Path(omarchy) / "config/omarchy/shell.json"):
        try:
            bar = json.loads(path.read_text()).get("bar", {})
        except (OSError, ValueError, AttributeError):
            continue
        if not isinstance(bar, dict):
            continue
        return not (bar.get("glassEnabled") is False or bar.get("glassLens") is False
                    or bar.get("glassReducedTransparency") is True or bar.get("glassHighContrast") is True)
    return True


def place(rects, fullscreen, monitor, layers):
    """Translate window rectangles to monitor-relative logical coordinates."""
    shell_pid = os.getppid()
    placed = []
    for entry in rects:
        window_w, window_h = (round(v) for v in entry["window"])
        x, y, w, h = map(float, entry["rect"])
        if entry.get("screen") not in ("", monitor["name"]) or w <= 0 or h <= 0:
            continue
        matches = [layer for layer in layers
                   if layer["pid"] == shell_pid and layer["w"] == window_w and layer["h"] == window_h]
        # Same-size windows are fine when they sit at the same origin, as the
        # full-screen launchers do; otherwise the rectangle cannot be placed.
        if not matches or len({(layer["x"], layer["y"]) for layer in matches}) != 1:
            continue
        layer = matches[0]
        if monitor["name"] in fullscreen and layer["level"] < 3:
            continue
        placed.append((layer["x"] - monitor["x"] + x, layer["y"] - monitor["y"] + y, w, h,
                       float(entry.get("radius", 0))))
    return placed[:MAX_RECTS]


def shader_source(rects, screen_w, screen_h):
    shapes, extras = [], []
    for x, y, w, h, radius in rects:
        band = max(2.0, min(10.0, min(w, h) * 0.12))
        shapes.append(f"vec4({(x + w / 2) / screen_w:.9f}, {(y + h / 2) / screen_h:.9f}, "
                      f"{w / 2 / screen_w:.9f}, {h / 2 / screen_h:.9f})")
        extras.append(f"vec2({radius / screen_w:.9f}, {band / screen_w:.9f})")
    count = len(rects)
    return f"""#version 300 es
// Generated by widget-on-glass-lens. Each rim samples the desktop just outside it.
precision highp float;
in vec2 v_texcoord;
layout(location = 0) out vec4 fragColor;
uniform sampler2D tex;
const int COUNT = {count};
const vec4 RECTS[COUNT] = vec4[COUNT]({", ".join(shapes)});
const vec2 SHAPES[COUNT] = vec2[COUNT]({", ".join(extras)});
void main() {{
    vec2 pixels = vec2(textureSize(tex, 0));
    vec4 original = texture(tex, v_texcoord);
    float weight = 0.0;
    vec2 offset = vec2(0.0);
    for (int i = 0; i < COUNT; i++) {{
        vec2 p = (v_texcoord - RECTS[i].xy) * pixels;
        vec2 halfSize = RECTS[i].zw * pixels;
        float radius = SHAPES[i].x * pixels.x;
        float band = SHAPES[i].y * pixels.x;
        if (any(greaterThan(abs(p), halfSize + 2.0))) continue;
        vec2 q = abs(p) - (halfSize - radius);
        float d = length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - radius;
        float edge = smoothstep(-band, -band * 0.5, d) * (1.0 - smoothstep(-band * 0.5, 2.0, d));
        if (edge > weight) {{
            vec2 outside = max(q, 0.0);
            vec2 normal = length(outside) > 0.0
                ? normalize(outside) * sign(p)
                : (q.x > q.y ? vec2(sign(p.x), 0.0) : vec2(0.0, sign(p.y)));
            weight = edge;
            offset = normal * (band - d) / pixels;
        }}
    }}
    if (weight > 0.0)
        fragColor = mix(original, texture(tex, clamp(v_texcoord + offset, 0.0, 1.0)), 0.28 * weight);
    else
        fragColor = original;
}}
"""


def apply(state):
    current = screen_shader()
    if not owned(current):
        raise SystemExit("screen_shader is already in use; leaving it untouched")
    monitors = [m for m in json.loads(hyprctl("-j", "monitors")) if not m.get("disabled")]
    rects = []
    # screen_shader runs on every monitor with no way to tell them apart, so
    # the lens is limited to a single unrotated monitor.
    if lens_allowed() and len(monitors) == 1 and monitors[0].get("transform", 0) == 0:
        monitor = monitors[0]
        layers = [dict(layer, level=int(level))
                  for name, data in json.loads(hyprctl("-j", "layers")).items() if name == monitor["name"]
                  for level, entries in data["levels"].items() for layer in entries]
        scale = monitor.get("scale", 1) or 1
        rects = place(state.get("rects", []), set(state.get("fullscreen", [])), monitor, layers)
        screen_w, screen_h = monitor["width"] / scale, monitor["height"] / scale
    if not rects:
        clear()
        return
    source = shader_source(rects, screen_w, screen_h)
    path = RUNTIME / f"{PREFIX}{hashlib.sha1(source.encode()).hexdigest()[:12]}.frag"
    if current != str(path):
        path.write_text(source)
        set_shader(path)
    remove_stale(keep=path)


def main(argv):
    if argv[1:] == ["clear"]:
        clear()
    elif len(argv) == 3 and argv[1] == "apply":
        apply(json.loads(argv[2]))
    else:
        raise SystemExit("usage: widget-on-glass-lens apply JSON | clear")


if __name__ == "__main__":
    try:
        main(sys.argv)
    except (OSError, ValueError, KeyError, TypeError, subprocess.CalledProcessError) as error:
        print(f"widget-on-glass lens: {error}", file=sys.stderr)
        raise SystemExit(1)
