#!/usr/bin/env python3
"""Build the Omarchy Glass marketplace plugin from the stock Omarchy shell.

The plugin replaces the bar and the menu, the two surfaces a third-party plugin
may own. It reuses the adapter's tested patches: they are applied to a scratch
copy of the stock shell, then the patched Bar.qml and Menu.qml are extracted
and pointed at the plugin's own glass components.

usage: build.py OUTPUT_DIR [--source /usr/share/omarchy]
"""

from pathlib import Path
import json
import re
import shutil
import subprocess
import sys
import tempfile

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parents[1]
sys.path.insert(0, str(PROJECT / "integrations/omarchy"))
import apply  # noqa: E402

PLUGIN_ID = "kitsuneforgering.glass"
VERSION = "0.1.0"
GENERATED = "// Generated by Widget-on-glass integrations/marketplace/build.py from Omarchy {omarchy}.\n"
RENAMES = (("GlassOverlay {", "PluginGlass {"), ("GlassScrim {", "PluginGlassScrim {"))


def omarchy_version(source: Path) -> str:
    try:
        out = subprocess.run(["pacman", "-Q", "omarchy"], capture_output=True, text=True, check=True).stdout
        return out.split()[1].rsplit("-", 1)[0]
    except (OSError, subprocess.CalledProcessError, IndexError):
        return "unknown"


def patched_shell(source: Path, scratch: Path) -> Path:
    checkout = scratch / "omarchy"
    shutil.copytree(source / "shell", checkout / "shell")
    (checkout / "bin").mkdir(parents=True)
    apply.patch_checkout(checkout)
    return checkout / "shell"


def rename(text: str) -> str:
    for before, after in RENAMES:
        text = text.replace(before, after)
    return text


def build_bar(shell: Path, header: str) -> str:
    path = shell / "plugins/bar/Bar.qml"
    bar = rename(path.read_text())
    bar = apply.replace_once(bar,
        "  readonly property bool glassEnabled: barConfig.glassEnabled !== false\n",
        "  readonly property bool glassEnabled: barConfig.glassEnabled !== false\n"
        "  Binding {\n"
        "    target: PluginGlassLens\n"
        "    property: \"allowed\"\n"
        "    value: root.glassEnabled && root.barConfig.glassLens !== false\n"
        "      && root.barConfig.glassReducedTransparency !== true && root.barConfig.glassHighContrast !== true\n"
        "  }\n", path)
    # The stock tray reserves its full drawer and only slides the content in.
    # An opaque bar hides the empty part; separate glass modules show it as a
    # full-width block. The shell's Tray.qml is not ours to patch, so the slot
    # shrinks by the hidden part and shifts the widget out of view instead.
    bar = apply.replace_once(bar,
        "    implicitWidth: activeItem && activeItem.visible ? (root.vertical ? root.barSize : activeItem.implicitWidth) : 0\n"
        "    implicitHeight: activeItem && activeItem.visible ? activeItem.implicitHeight : 0\n",
        "    readonly property real hiddenExtent: activeItem && \"drawerExtent\" in activeItem && \"revealExtent\" in activeItem\n"
        "      ? Math.max(0, activeItem.drawerExtent - activeItem.revealExtent) : 0\n"
        "    implicitWidth: activeItem && activeItem.visible ? (root.vertical ? root.barSize : activeItem.implicitWidth - hiddenExtent) : 0\n"
        "    implicitHeight: activeItem && activeItem.visible ? activeItem.implicitHeight - (root.vertical ? hiddenExtent : 0) : 0\n",
        path)
    bar = apply.replace_once(bar,
        "      sourceComponent: slot.registered ? slot.registryComponent : null\n      anchors.fill: parent\n",
        "      sourceComponent: slot.registered ? slot.registryComponent : null\n"
        "      x: root.vertical ? 0 : -slot.hiddenExtent\n"
        "      y: root.vertical ? -slot.hiddenExtent : 0\n"
        "      width: slot.width + (root.vertical ? 0 : slot.hiddenExtent)\n"
        "      height: slot.height + (root.vertical ? slot.hiddenExtent : 0)\n", path)
    return header + bar


def build_menu(shell: Path, header: str) -> str:
    path = shell / "plugins/menu/Menu.qml"
    menu = rename(path.read_text())
    # The shell's BorderSurface carries no glass here, so the selected row
    # gets its rim directly.
    menu = apply.replace_once(menu,
        "              borderSpec: row.hasCursor ? root.selectedBorderSpec : Border.none()\n",
        "              borderSpec: row.hasCursor ? root.selectedBorderSpec : Border.none()\n"
        "              PluginGlass { z: 50; anchors.fill: parent; radius: row.radius; visible: row.hasCursor; "
        "reflectionOnly: true; lens: true }\n", path)
    menu = menu.replace("summon omarchy.menu", f"summon {PLUGIN_ID}")
    return header + menu


def build_button(shell: Path, header: str) -> str:
    path = shell / "plugins/menu/BarWidget.qml"
    button = path.read_text()
    button = apply.replace_once(button, 'moduleName: "omarchy.menu"', f'moduleName: "{PLUGIN_ID}"', path)
    button = apply.replace_once(button, "shell toggle omarchy.menu", f"shell toggle {PLUGIN_ID}", path)
    return header + button


def build(output: Path, source: Path) -> None:
    omarchy = omarchy_version(source)
    header = GENERATED.format(omarchy=omarchy)
    output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as scratch:
        shell = patched_shell(source, Path(scratch))
        files = {
            "Bar.qml": build_bar(shell, header),
            "Menu.qml": build_menu(shell, header),
            "MenuButton.qml": build_button(shell, header),
            "BarModel.js": (shell / "plugins/bar/BarModel.js").read_text(),
            "MenuModel.js": (shell / "plugins/menu/MenuModel.js").read_text(),
            "PluginGlass.qml": (PROJECT / "src/GlassOverlay.qml").read_text()
                .replace("GlassLens.", "PluginGlassLens.").replace("and GlassLens asks", "and PluginGlassLens asks")
                .replace('"GlassOverlay:"', '"PluginGlass:"'),
            "PluginGlassScrim.qml": (PROJECT / "src/GlassScrim.qml").read_text(),
            "PluginGlassLens.qml": (HERE / "PluginGlassLens.qml").read_text(),
            "qmldir": "singleton PluginGlassLens 1.0 PluginGlassLens.qml\n"
                      "PluginGlass 1.0 PluginGlass.qml\n"
                      "PluginGlassScrim 1.0 PluginGlassScrim.qml\n",
        }
    for name, text in files.items():
        if re.search(r"(?<!Plugin)Glass(Overlay|Scrim|Lens)\b\s*[{.]", text):
            raise ValueError(f"{name} still references the shell's glass components")
        (output / name).write_text(text)

    shaders = output / "shaders"
    shaders.mkdir(exist_ok=True)
    shutil.copy2(PROJECT / "src/shaders/overlay.frag", shaders / "overlay.frag")
    subprocess.run(["/usr/lib/qt6/bin/qsb", "--glsl", "100 es,120,150", "--hlsl", "50", "--msl", "12",
                    "-o", str(shaders / "overlay.frag.qsb"), str(shaders / "overlay.frag")], check=True)

    manifest = {
        "schemaVersion": 1,
        "id": PLUGIN_ID,
        "name": "Glass",
        "version": VERSION,
        "author": "KitsuneForgering",
        "description": "Translucent glass bar and menu with blur, rim light and a desktop-refracting rim lens",
        "kinds": ["bar", "menu", "bar-widget"],
        "keepLoaded": True,
        "entryPoints": {"bar": "Bar.qml", "menu": "Menu.qml", "barWidget": "MenuButton.qml"},
        "barWidget": {
            "displayName": "Glass menu",
            "description": "Opens the glass Omarchy menu",
            "category": "Compositor",
            "allowMultiple": False,
            "defaultSection": "left",
        },
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    for name in ("README.md", "LICENSE", "preview.png"):
        shutil.copy2(HERE / name, output / name)
    print(f"built {PLUGIN_ID} {VERSION} from Omarchy {omarchy} into {output}")


if __name__ == "__main__":
    args = sys.argv[1:]
    source = Path("/usr/share/omarchy")
    if "--source" in args:
        index = args.index("--source")
        source = Path(args[index + 1])
        del args[index:index + 2]
    if len(args) != 1:
        raise SystemExit(__doc__)
    build(Path(args[0]).resolve(), source)
