pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Hyprland
import Quickshell.Io

// Plugin build of GlassLens: collects the visible glass rectangles and turns
// them into one Hyprland screen_shader rim lens. Omarchy does not ship Python,
// so this queries Hyprland and writes the shader itself. Another shader that
// the user configured is never replaced.
Singleton {
    id: root

    // The bar binds this to the glass switches in shell.json.
    property bool allowed: true
    readonly property string prefix: "omarchy-glass-lens-"
    readonly property string runtimeDir: Quickshell.env("XDG_RUNTIME_DIR") || "/tmp"
    readonly property int maxRects: 32
    property var overlays: []
    property string sent: ""
    property string pending: ""
    property bool dirty: false

    function register(overlay) {
        if (overlays.indexOf(overlay) < 0) overlays = overlays.concat([overlay])
        schedule()
    }

    function unregister(overlay) {
        overlays = overlays.filter(o => o !== overlay)
        schedule()
    }

    function schedule() {
        debounce.restart()
    }

    function snapshot() {
        const rects = []
        if (allowed) {
            for (const overlay of overlays) {
                const rect = overlay.lensRect()
                if (rect) rects.push(rect)
            }
        }
        const fullscreen = Hyprland.monitors.values
            .filter(m => m.activeWorkspace && m.activeWorkspace.hasFullscreen)
            .map(m => m.name)
        return JSON.stringify({ rects: rects, fullscreen: fullscreen })
    }

    function busy() {
        return query.running || writer.running
    }

    function update() {
        const state = snapshot()
        if (state === sent) return
        if (busy()) { dirty = true; return }
        sent = state
        pending = state
        query.running = true
    }

    function finished() {
        if (!busy() && dirty) { dirty = false; update() }
    }

    function unset(path) {
        return path === "" || path === "[[EMPTY]]"
    }

    function owned(path) {
        return unset(path) || path.split("/").pop().startsWith(prefix)
    }

    // Window rectangles to monitor-relative logical coordinates. A window is
    // found by this shell's PID and its size; same-size windows at different
    // origins are ambiguous and stay out of the lens.
    function place(rects, fullscreen, monitor, layers) {
        const placed = []
        for (const entry of rects) {
            const [x, y, w, h] = entry.rect
            if ((entry.screen && entry.screen !== monitor.name) || w <= 0 || h <= 0) continue
            const matches = layers.filter(l => l.pid === Quickshell.processId
                && l.w === Math.round(entry.window[0]) && l.h === Math.round(entry.window[1]))
            if (!matches.length || matches.some(l => l.x !== matches[0].x || l.y !== matches[0].y)) continue
            const layer = matches[0]
            if (fullscreen.indexOf(monitor.name) >= 0 && layer.level < 3) continue
            placed.push([layer.x - monitor.x + x, layer.y - monitor.y + y, w, h, entry.radius || 0])
        }
        return placed.slice(0, maxRects)
    }

    function shaderSource(rects, screenW, screenH) {
        const n = v => v.toFixed(9)
        const shapes = rects.map(([x, y, w, h]) =>
            `vec4(${n((x + w / 2) / screenW)}, ${n((y + h / 2) / screenH)}, ${n(w / 2 / screenW)}, ${n(h / 2 / screenH)})`)
        const extras = rects.map(([x, y, w, h, radius]) =>
            `vec2(${n(radius / screenW)}, ${n(Math.max(2, Math.min(10, Math.min(w, h) * 0.12)) / screenW)})`)
        return `#version 300 es
// Generated by the Omarchy Glass plugin. Each rim samples the desktop just outside it.
precision highp float;
in vec2 v_texcoord;
layout(location = 0) out vec4 fragColor;
uniform sampler2D tex;
const int COUNT = ${rects.length};
const vec4 RECTS[COUNT] = vec4[COUNT](${shapes.join(", ")});
const vec2 SHAPES[COUNT] = vec2[COUNT](${extras.join(", ")});
void main() {
    vec2 pixels = vec2(textureSize(tex, 0));
    vec4 original = texture(tex, v_texcoord);
    float weight = 0.0;
    vec2 offset = vec2(0.0);
    for (int i = 0; i < COUNT; i++) {
        vec2 p = (v_texcoord - RECTS[i].xy) * pixels;
        vec2 halfSize = RECTS[i].zw * pixels;
        float radius = SHAPES[i].x * pixels.x;
        float band = SHAPES[i].y * pixels.x;
        if (any(greaterThan(abs(p), halfSize + 2.0))) continue;
        vec2 q = abs(p) - (halfSize - radius);
        float d = length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - radius;
        float edge = smoothstep(-band, -band * 0.5, d) * (1.0 - smoothstep(-band * 0.5, 2.0, d));
        if (edge > weight) {
            vec2 outside = max(q, 0.0);
            vec2 normal = length(outside) > 0.0
                ? normalize(outside) * sign(p)
                : (q.x > q.y ? vec2(sign(p.x), 0.0) : vec2(0.0, sign(p.y)));
            weight = edge;
            offset = normal * (band - d) / pixels;
        }
    }
    if (weight > 0.0)
        fragColor = mix(original, texture(tex, clamp(v_texcoord + offset, 0.0, 1.0)), 0.28 * weight);
    else
        fragColor = original;
}
`
    }

    function hash(text) {
        let h = 5381
        for (let i = 0; i < text.length; i++) h = ((h * 33) ^ text.charCodeAt(i)) >>> 0
        return h.toString(16)
    }

    function setShader(path, source) {
        const lua = `hl.config({ decoration = { screen_shader = ${JSON.stringify(path)} } })`
        writer.command = ["sh", "-c",
            '[ -z "$2" ] || printf "%s" "$1" > "$2" || exit 1\n'
            + 'hyprctl eval "$3" >/dev/null || exit 1\n'
            + 'find "$4" -maxdepth 1 -name "$5*.frag" ! -path "${2:-/}" -delete',
            "sh", source, path, lua, runtimeDir, prefix]
        writer.running = true
    }

    function apply(output) {
        let option, monitors, layers
        try { [option, monitors, layers] = JSON.parse(output) } catch (error) { return }
        const current = String(option.str || "")
        if (!owned(current)) return
        const state = JSON.parse(pending)
        const active = monitors.filter(m => !m.disabled)
        // screen_shader runs on every monitor with no way to tell them apart.
        let rects = []
        let monitor = null
        if (active.length === 1 && !active[0].transform) {
            monitor = active[0]
            const list = []
            for (const level in (layers[monitor.name] || { levels: {} }).levels)
                for (const layer of layers[monitor.name].levels[level])
                    list.push(Object.assign({ level: Number(level) }, layer))
            rects = place(state.rects, state.fullscreen, monitor, list)
        }
        if (!rects.length) {
            if (!unset(current)) setShader("", "")
            return
        }
        const scale = monitor.scale || 1
        const source = shaderSource(rects, monitor.width / scale, monitor.height / scale)
        const path = `${runtimeDir}/${prefix}${hash(source)}.frag`
        if (path !== current) setShader(path, source)
    }

    Timer { id: debounce; interval: 60; onTriggered: root.update() }
    // Parents move and animate without telling their children; polling the
    // few registered rectangles is cheaper than wiring every ancestor.
    Timer { interval: 300; repeat: true; running: true; onTriggered: root.update() }

    Process {
        id: query
        command: ["sh", "-c", "printf '['; hyprctl -j getoption decoration:screen_shader; printf ','; "
            + "hyprctl -j monitors; printf ','; hyprctl -j layers; printf ']'"]
        stdout: StdioCollector { onStreamFinished: root.apply(text) }
        onRunningChanged: if (!running) Qt.callLater(root.finished)
    }

    Process {
        id: writer
        onRunningChanged: if (!running) root.finished()
    }

    onAllowedChanged: { sent = ""; schedule() }

    Connections {
        target: Hyprland
        // A config reload resets screen_shader; resend the current lens.
        function onRawEvent(event) {
            if (event.name === "configreloaded") { root.sent = ""; root.schedule() }
        }
    }

    Component.onDestruction: Quickshell.execDetached(["sh", "-c",
        'case "$(hyprctl -j getoption decoration:screen_shader)" in *"$1"*) '
        + 'hyprctl eval \'hl.config({ decoration = { screen_shader = "" } })\' >/dev/null ;; esac; '
        + 'find "$2" -maxdepth 1 -name "$1*.frag" -delete', "sh", prefix, runtimeDir])
}
